version: 2

registries:
  github-doguu:
    type: git
    url: https://github.com
    username: 1s22s1
    password: ${{secrets.DOGUU}

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    registries:
      - github-doguu
    schedule:
      interval: "weekly"
