version: 2

registries:
  github-doguu:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.DOGUU}

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    registries:
      - doguu-github
    schedule:
      interval: "weekly"
